### PR TITLE
Added some more debug messages and updated Kenwood KY string.

### PR DESCRIPTION
**Pull request by ny4i**
The KY string is now KY characters      ;. I want to see if this handles
changes things at all.
I also added some better debug messages and a timestamp.
Changed the display color to blue as well (Yellow hurt my eyes).

### CODE REVIEW

**Comment by n4af** [comment]
Hi Tom -
Basically the same with both K3 and ts590. 73, Howie
cwbc-k3

**Comment by n4af** [comment]
I am still showing the yellow bg ?? But it is showing characters. I need cwbc_sending to go false tho

**Comment by ny4i** [comment]
If you are showing yellow, you are not running my changes. How are you
getting pull request. I can merge into master too.

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Mar 4, 2016, at 6:53 AM, Howie Hoyt <notifications@github.com> wrote:

I am still showing the yellow bg ?? But it is showing characters. I need
cwbc_sending to go false tho

—
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/pull/134#issuecomment-192252815>.

**Comment by n4af** [comment]
i am fetching Issue130 and merging ?

http://n4af.net

**Pull request merged**
