### PR TITLE
Cw by cat and speed sync touchups

### PR DESCRIPTION
**Pull request by ny4i**

### CODE REVIEW

**Comment by ny4i** [comment]
I documented the issues in the comments. This branch also added new rigs. I did them in separate commits.

**Comment by n4af** [comment]
ok. guess i better switch back as i am not on the new branch

http://n4af.net

**Comment by ny4i** [comment]
Before you merge, pull this one and give it a spin.

**Comment by n4af** [comment]
i think that is the one i just put up on tr4w.net
http://tr4w.net/4.46/tr4w_setup_4_46.11.exe

nice to see all the kenwoods.
no joy trying to communicate with cat as ts590s though.

73, Howie

http://n4af.net

**Comment by ny4i** [comment]
Ok. Under radio one dialogue, you have no CW settings, right?

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Feb 28, 2016, at 4:28 PM, Howie Hoyt <notifications@github.com> wrote:

i think that is the one i just put up on tr4w.net
http://tr4w.net/4.46/tr4w_setup_4_46.11.exe

nice to see all the kenwoods.
no joy trying to communicate with cat as ts590s though.

73, Howie

http://n4af.net

On Sun, Feb 28, 2016 at 3:46 PM, Tom Schaefer <notifications@github.com>
wrote:

> Before you merge, pull this one and give it a spin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/n4af/TR4W/pull/123#issuecomment-189943147>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/pull/123#issuecomment-189945872>.

**Comment by n4af** [comment]
not sure i follow you Tom.
Hardware diaglog for Radio 1 has full settings for TS590. But radio one
freq does not show up in tr4w unless i set as ts850/k3 ?

73, Howie

http://n4af.net

**Comment by ny4i** [comment]
I just meant to make sure that the second frame option KEYER RADIO PORT OUTPUT PORT = NONE
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
Oh, sorry- been on Wkey toooooo long.
Yeah it is 'none'

73, Howie

http://n4af.net

**Comment by n4af** [comment]
Hi Tom -

Could you describe how you generated this ?

Did you simply click on 'pull request' ?

Very nice.

73, Howie


http://n4af.net

**Comment by ny4i** [comment]
After I committed and pushed my changes to origin, I used the GitHub to create a Pull request from this branch. I believe I selected the branch from the drop down and clicked the green button that said to create a pull request.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
i forced changes to master that change the order the buffer is built in for new Kenwoods (to eliminate extra spaces).
Also second press of escape key now triggers InitializeQSO
4.46.11 updated with change

**Comment by ny4i** [comment]
Does the ESC key work ok in s&p?

I saw where one press stopped sending and the second went back to CQ mode.

Tom

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Feb 29, 2016, at 9:45 PM, Howie Hoyt <notifications@github.com> wrote:

i forced changes to master that change the order the buffer is built in for
new Kenwoods (to eliminate extra spaces).
Also second press of escape key now triggers InitializeQSO
4.46.11 updated with change

—
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/pull/123#issuecomment-190507447>.

**Comment by n4af** [comment]
yeah, it has too many legs. Strictly pop-a-gopher.

I will worry about it tomorrow.



http://n4af.net

**Pull request merged**
