### PR TITLE
Fixed exporting the state

### PR DESCRIPTION
**Pull request by ny4i**
I fixed exporting the state bu adding more intelligence to the process. The code was looking at DomesticMults but that was wrong. I changed this to look at the contestsArray[contest].DF field to see if it was arrlsect and also to only emit the STATE ADIF field if we can really calculate a valid state.

### CODE REVIEW

**Comment by ny4i** [comment]
This closes #463. It is ready to go.

**Comment by n4af** [comment]
FB. Integrated into 4.94.4

**Comment by ny4i** [comment]
Howie,

Did you integrate this pull request into Master on GitHub? I ask as it is usually closed when it is integrated. Thanks, Tom

**Comment by n4af** [comment]
no i manually pulled it, pls test 4.94.4 to guarantee all ok ?

**Pull request merged**
