### PR TITLE
Added edit to dialogs and code

### LINKED ISSUE #601: Allow OPERATOR field to be edited in the Edit QSO Dialog
Operator is missing from the dialog to edit. Add this so it can be edited.

### PR DESCRIPTION
**Pull request by ny4i**
Modified the code to allow editing the OPERATOR field in the edit dialog. Updated all the language dialog resource files to add OPERATOR field (FLD_OPERATOR_ as number 167. This closes #601.

### CODE REVIEW

**Comment by ok1rr** [comment]
Found a bug in 4.124.3 IARU HF

The AutoSend does not wait until the callsign sending is completed and 
jumps into the exchange line immediately when the character at AUTO SEND 
CHARACTER COUNT position is typed in. It should follow the sending but 
it does not... Hard to describe but a test would say all...

73,
Martin, OK1RR

**Comment by ok1rr** [comment]
BTW 4.123.9 works perfectly...

73 RR

**Comment by n4af** [comment]
well, for me, 4.124.2, 4.123.3, 4.124 work perfectly.

AUTO SEND CHARACTER COUNT = 3
AUTO CALL TERMINATE = TRUE
Sending starts at 3rd character,  I enter 'ITU' whilst sending '4U1' and
'4u1itu' is sent along with a carriage return.

Maybe I do not understand the complaint ??

**Comment by ok1rr** [comment]
4.124.4 works perfectly...

73 RR

**Comment by n4af** [comment]
i do not want to hijack this issue- which is not related.
closing and moving to the forum.

**Pull request merged**
