### PR TITLE
Update uSpots.pas

### PR DESCRIPTION
**Pull request by ny4i**

### CODE REVIEW

**Comment by ny4i** [comment]
We have to make sure we do not release that if it crashes and burns. I appreciate if you can test it out under load (and with two bandmaps going with two radios).

Thanks,

Tom

**Comment by n4af** [comment]
[fix 4.135.4](https://www.tr4w.net/4.135/tr4w_setup_4_135.4.exe)

**Comment by n4af** [comment]
Running under telnet.reversebeacon.net, to simulate hight contest spots,
all seems ok so far.

Something like  upcoming WPXCW should be a good test.

**Comment by ny4i** [comment]
Maybe I will run this one myself to test as I would hate to mess everyone up in the middle of WPX.

Tom

**Comment by ny4i** [comment]
Howie - Do you recall some of the things we were thinking of to stop the flashing. I believe one was to delay the updates a bit. The spots should stay in sync now that the SpotList is protected by a lock.

Tom

**Comment by n4af** [comment]
Hi Tom -
Well, I emphasized heavier filtering of the spots.
But in a big contest that may not be enuff.

I think the other thing I tried was to write the spots to a buffer and
every (x) spots, write the buffer out.

**Comment by ny4i** [comment]
What if we just did the redraw on a timer every 1 second?TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771813-205-6388 (mobile/text)On May 17, 2024, at 1:48 PM, Howie Hoyt ***@***.***> wrote:﻿
Hi Tom -

Well, I emphasized heavier filtering of the spots.

But in a big contest that may not be enuff.



I think the other thing I tried was to write the spots to a buffer and

every (x) spots, write the buffer out.







On Fri, May 17, 2024 at 12:08 PM Tom Schaefer ***@***.***>

wrote:



> Howie - Do you recall some of the things we were thinking of to stop the

> flashing. I believe one was to delay the updates a bit. The spots should

> stay in sync now that the SpotList is protected by a lock.

>

> Tom

>

**Comment by n4af** [comment]
so, you are thinking of buffering telnet spots and every second dump them
into ProcessDX ?

**Comment by ny4i** [comment]
Not exactly. I was thinking let the packets get processed and put in the list but not do the redraw immediately. Just have a timer do the redraw every time it fires ( 1 second intervals). I can try it and see how it works. TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771813-205-6388 (mobile/text)On May 17, 2024, at 5:10 PM, Howie Hoyt ***@***.***> wrote:﻿
so, you are thinking of buffering telnet spots and every second dump them

into ProcessDX ?



On Fri, May 17, 2024 at 4:16 PM Tom Schaefer ***@***.***>

wrote:



> What if we just did the redraw on a timer every 1 second?TomPrincipal

> Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771813-205-6388

> (mobile/text)On May 17, 2024, at 1:48 PM, Howie Hoyt ***@***.***> wrote:﻿

> Hi Tom -

>

> Well, I emphasized heavier filtering of the spots.

>

> But in a big contest that may not be enuff.

>

>

>

> I think the other thing I tried was to write the spots to a buffer and

>

> every (x) spots, write the buffer out.

>

>

>

>

>

>

>

> On Fri, May 17, 2024 at 12:08 PM Tom Schaefer ***@***.***>

>

> wrote:

>

>

>

> > Howie - Do you recall some of the things we were thinking of to stop the

>

> > flashing. I believe one was to delay the updates a bit. The spots should

>

> > stay in sync now that the SpotList is protected by a lock.

>

> >

>

> > Tom

>

> >

>

**Comment by n4af** [comment]
i think the problem with that is the bandmap buffer vs flist buffer but my
recall of the problem is poor- just that there was a buffer mismatch
where you clicked on a spot only to bring up the wrong spot...

**Pull request merged**
