### PR TITLE
Added confirmation dialog after upload or on error

### LINKED ISSUE #592: Add an API to send Cabrillo to SCP collection  (presently K6TU)
Watchful users of Super Check Partial will see a significant increase in the number of callsigns in MASTER and its derived files.  This month’s release (just posted live) has 40,940 calls in MASTER – up from 35,416 last month.

This step function in active calls is a result of a new API which allows logging programs to directly submit a log to Super Check Partial.  This removes the need for the contester to take the extra step of emailing the log to [logs@supercheckpartial.com](mailto:logs@supercheckpartial.com)<mailto:[logs@supercheckpartial.com](mailto:logs@supercheckpartial.com)>.  Logs are submitted securely to Super Check Partial over HTTPS and are “signed” by the logging program before submission to authenticate the origin of the log.

SCP API support has already been added to N1MM+, DXLog.net, SkookumLogger, N3FJP’s loggers and Writelog.  This support is in published releases for N1MM+ and DXLog.net, selected contests for N3FJP loggers  and in beta versions for SkookumLogger and Writelog.

The supporting logging programs ask the contester for their consent to upload the log to Super Check Partial – by design this is an opt-in process.  Logs are NOT submitted without the contester’s consent.

### PR DESCRIPTION
**Pull request by ny4i**
Fixed #592 

Added Yes/No after the Cabrillo preview window is closed to ask if the user wants to upload the log file.

### CODE REVIEW

**Comment by n4af** [comment]
Hi Tom -
All seems f.b. 
I now rx 'Log file succesfully uploaded to SuperCheckPartial'
That only occured after error re: DLL and then recalled a need to bring the DLL's in- which I added to
the build process.
This generated as 4.110.2 but suppose it might be good to overlay that with a later 4.110.2-- if you plan to 
mod for tc_whatever language support ?

**Comment by ny4i** [comment]
I put the DLLs in the TARGET directory on GitHub but as long as you add them in the build process, that works too. I will let you know if we have a new (and critical) OpenSSL DLL as I need to keep up on that for work.

I have more changes this month anyway so I will pick it up eventually.

I guess it is time to let the user’s know what we did to get some feedback.

Tom


Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n4af** [comment]
[to 4.110.2](https://tr4w.net/4.110/tr4w_setup_4_110.2.exe)

**Comment by ny4i** [comment]
Neither Chrome or Edge would let me download the file.

I was reading that files that are .msi install files are not as suspicious as .EXE files.

Is it possible to create an msg file with the tool you use to build? I’m just asking to try and solve this problem.

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n4af** [comment]
i will refrain from comments on ms$.
Looking into Wix right now.

73, Howie

**Pull request merged**
