### PR TITLE
Fixes #141 and #105

### LINKED ISSUE #141: Bandmap does not clear all spots cleanly
Clearing all spots leaves spurious characters for a short period

### PR DESCRIPTION
**Pull request by gm0gav**
#141 Added Kllfocus procedure to cleanly move focus from Bandmap,
resolves issue of rubbish left in bandmap after clear all spots.

#105 Resolved issue of bandmap flipping band on every ptt event. Now
only changes the bandmap band when the frequency changes.

### CODE REVIEW

**Comment by ny4i** [comment]
Outstanding! Welcome back :)

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Mar 30, 2016, at 2:23 PM, gm0gav <notifications@github.com> wrote:

#141 <https://github.com/n4af/TR4W/issues/141> Added Kllfocus procedure to
cleanly move focus from Bandmap,
resolves issue of rubbish left in bandmap after clear all spots.

#105 <https://github.com/n4af/TR4W/issues/105> Resolved issue of bandmap
flipping band on every ptt event. Now
only changes the bandmap band when the frequency changes.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/n4af/TR4W/pull/161
Commit Summary

   - 4.47.1 Issue 135 Split Dialog box added
   - 4.47.2 toggle split issue 136
   - 4.47.3 issue # 125
   - Gav issue #105
   - Revert "Gav issue #105"
   - Fixes #141 and #105

File Changes

   - *M* tr4w/src/MainUnit.pas
   <https://github.com/n4af/TR4W/pull/161/files#diff-0> (63)
   - *M* tr4w/src/VC.pas
   <https://github.com/n4af/TR4W/pull/161/files#diff-1> (8)
   - *M* tr4w/src/lang/tr4w_consts_mng.pas
   <https://github.com/n4af/TR4W/pull/161/files#diff-2> (18)
   - *M* tr4w/src/trdos/LOGK1EA.PAS
   <https://github.com/n4af/TR4W/pull/161/files#diff-3> (2)
   - *M* tr4w/src/trdos/LOGRADIO.PAS
   <https://github.com/n4af/TR4W/pull/161/files#diff-4> (4)
   - *M* tr4w/src/uBandmap.pas
   <https://github.com/n4af/TR4W/pull/161/files#diff-5> (23)
   - *M* tr4w/src/uMenu.pas
   <https://github.com/n4af/TR4W/pull/161/files#diff-6> (7)
   - *M* tr4w/src/uRadioPolling.pas
   <https://github.com/n4af/TR4W/pull/161/files#diff-7> (22)

Patch Links:

   - https://github.com/n4af/TR4W/pull/161.patch
   - https://github.com/n4af/TR4W/pull/161.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/pull/161>

**Comment by n4af** [comment]
wow, i am having trouble integrating this. A lot of merge conflicts. in
most cases the code d/n have comments.

Tom -
can you have a look ? I suspect you can figure out the conflict in uradio ?

The present master is 4.48 plus issue153

Tks, Howie

http://n4af.net

**Comment by ny4i** [comment]
I will look.

Gav, did you fetch and pull the latest master before you started your work
on these?

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Mar 30, 2016, at 5:10 PM, Howie Hoyt <notifications@github.com> wrote:

wow, i am having trouble integrating this. A lot of merge conflicts. in
most cases the code d/n have comments.

Tom -
can you have a look ? I suspect you can figure out the conflict in uradio ?

The present master is 4.48 plus issue153

Tks, Howie

http://n4af.net

On Wed, Mar 30, 2016 at 2:23 PM, gm0gav <notifications@github.com> wrote:

> #141 <https://github.com/n4af/TR4W/issues/141> Added Kllfocus procedure
> to cleanly move focus from Bandmap,
> resolves issue of rubbish left in bandmap after clear all spots.
>
> #105 <https://github.com/n4af/TR4W/issues/105> Resolved issue of bandmap
> flipping band on every ptt event. Now
> only changes the bandmap band when the frequency changes.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/n4af/TR4W/pull/161
> Commit Summary
>
> - 4.47.1 Issue 135 Split Dialog box added
> - 4.47.2 toggle split issue 136
> - 4.47.3 issue # 125
> - Gav issue #105
> - Revert "Gav issue #105"
> - Fixes #141 and #105
>
> File Changes
>
> - *M* tr4w/src/MainUnit.pas
> <https://github.com/n4af/TR4W/pull/161/files#diff-0> (63)
> - *M* tr4w/src/VC.pas
> <https://github.com/n4af/TR4W/pull/161/files#diff-1> (8)
> - *M* tr4w/src/lang/tr4w_consts_mng.pas
> <https://github.com/n4af/TR4W/pull/161/files#diff-2> (18)
> - *M* tr4w/src/trdos/LOGK1EA.PAS
> <https://github.com/n4af/TR4W/pull/161/files#diff-3> (2)
> - *M* tr4w/src/trdos/LOGRADIO.PAS
> <https://github.com/n4af/TR4W/pull/161/files#diff-4> (4)
> - *M* tr4w/src/uBandmap.pas
> <https://github.com/n4af/TR4W/pull/161/files#diff-5> (23)
> - *M* tr4w/src/uMenu.pas
> <https://github.com/n4af/TR4W/pull/161/files#diff-6> (7)
> - *M* tr4w/src/uRadioPolling.pas
> <https://github.com/n4af/TR4W/pull/161/files#diff-7> (22)
>
> Patch Links:
>
> - https://github.com/n4af/TR4W/pull/161.patch
> - https://github.com/n4af/TR4W/pull/161.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/n4af/TR4W/pull/161>
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/pull/161#issuecomment-203637317>

**Comment by gm0gav** [comment]
I will qrx until you guts figure out the conflicts, will do tomorrow

73 Gav

**Comment by ny4i** [comment]
But if you could share the last time you pulled master that would be
helpful.

Thanks

Tom

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Mar 30, 2016, at 5:45 PM, gm0gav <notifications@github.com> wrote:


I will qrx until you guts figure out the conflicts, will do tomorrow

73 Gav



On 30/03/2016 21:14, Tom Schaefer wrote:
> I will look.
>
> Gav, did you fetch and pull the latest master before you started your work
> on these?
>
> Principal Solutions Architect
> Better Software Solutions, Inc.
> 727-437-2771
>
> On Mar 30, 2016, at 5:10 PM, Howie Hoyt <notifications@github.com> wrote:
>
> wow, i am having trouble integrating this. A lot of merge conflicts. in
> most cases the code d/n have comments.
>
> Tom -
> can you have a look ? I suspect you can figure out the conflict in
> uradio ?
>
> The present master is 4.48 plus issue153
>
> Tks, Howie
>
> http://n4af.net
>
> On Wed, Mar 30, 2016 at 2:23 PM, gm0gav <notifications@github.com> wrote:
>
> > #141 <https://github.com/n4af/TR4W/issues/141> Added Kllfocus procedure
> > to cleanly move focus from Bandmap,
> > resolves issue of rubbish left in bandmap after clear all spots.
> >
> > #105 <https://github.com/n4af/TR4W/issues/105> Resolved issue of bandmap
> > flipping band on every ptt event. Now
> > only changes the bandmap band when the frequency changes.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/n4af/TR4W/pull/161
> > Commit Summary
> >
> > - 4.47.1 Issue 135 Split Dialog box added
> > - 4.47.2 toggle split issue 136
> > - 4.47.3 issue # 125
> > - Gav issue #105
> > - Revert "Gav issue #105"
> > - Fixes #141 and #105
> >
> > File Changes
> >
> > - *M* tr4w/src/MainUnit.pas
> > <https://github.com/n4af/TR4W/pull/161/files#diff-0> (63)
> > - *M* tr4w/src/VC.pas
> > <https://github.com/n4af/TR4W/pull/161/files#diff-1> (8)
> > - *M* tr4w/src/lang/tr4w_consts_mng.pas
> > <https://github.com/n4af/TR4W/pull/161/files#diff-2> (18)
> > - *M* tr4w/src/trdos/LOGK1EA.PAS
> > <https://github.com/n4af/TR4W/pull/161/files#diff-3> (2)
> > - *M* tr4w/src/trdos/LOGRADIO.PAS
> > <https://github.com/n4af/TR4W/pull/161/files#diff-4> (4)
> > - *M* tr4w/src/uBandmap.pas
> > <https://github.com/n4af/TR4W/pull/161/files#diff-5> (23)
> > - *M* tr4w/src/uMenu.pas
> > <https://github.com/n4af/TR4W/pull/161/files#diff-6> (7)
> > - *M* tr4w/src/uRadioPolling.pas
> > <https://github.com/n4af/TR4W/pull/161/files#diff-7> (22)
> >
> > Patch Links:
> >
> > - https://github.com/n4af/TR4W/pull/161.patch
> > - https://github.com/n4af/TR4W/pull/161.diff
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/n4af/TR4W/pull/161>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/n4af/TR4W/pull/161#issuecomment-203637317>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/n4af/TR4W/pull/161#issuecomment-203638251>
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/pull/161#issuecomment-203648129>

**Comment by n4af** [comment]
Hi Guys -

I have taken a swag at getting things to compile on 4.48.1
(pull 161)

I notice that alt-d does not work ? The bandmap entry goes red, but the
alt-d window d/n load.

Gav -
Could you check your pull level and see if it works there ?

The executable code is at http://tr4w.net/4.48/tr4w_setup_4_48.1.exe but i
have not pushed anything up to the repo yet.

Tks, Howie

http://n4af.net

**Pull request merged**
